# Generated by Django 2.1.4 on 2019-07-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190717_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='likes',
            field=models.TextField(default=''),
        ),
    ]
